// Writes src/config.js from .env.local (or from environment variables on a host like Netlify/Vercel).
// Run: npm run config
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const env = { ...process.env };
if (existsSync('.env.local')) {
  for (const line of readFileSync('.env.local', 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.*?)\s*$/);
    if (m && !line.trim().startsWith('#') && !(m[1] in process.env)) env[m[1]] = m[2];
  }
}

const url = env.SUPABASE_URL || 'https://YOUR-PROJECT.supabase.co';
const key = env.SUPABASE_KEY || 'YOUR-ANON-KEY';
const ai = env.AI_ENABLED !== 'false';

writeFileSync('src/config.js', `// GENERATED by scripts/generate-config.js from .env.local. Do not edit or commit.
export const config = {
  SUPABASE_URL: ${JSON.stringify(url)},
  SUPABASE_KEY: ${JSON.stringify(key)},
  AI_ENABLED: ${ai},
};

export const isConfigured = Boolean(
  config.SUPABASE_URL && config.SUPABASE_KEY && !config.SUPABASE_URL.includes('YOUR-PROJECT'),
);

export const aiEnabled = isConfigured && config.AI_ENABLED;
`);
console.log('src/config.js written');
